version: '3.1'

services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=game_sales

  etl:
    depends_on:
      - db
    container_name: etl
    image: etl
    environment:
      - DATABASE=game_sales
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=mysecretpassword
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - AWS_ACCESS_KEY_ID=AKIAW4TA5K32FQ3FXT47
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=us-east-1
